{% set name = "pickydict" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pickydict-{{ version }}.tar.gz
  sha256: 2a3cd92d3f21c9f4591c1df95a312cae5f9243ba133ff258b1eb91c46b3df40b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pickydict
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/florian-huber/pickydict
  summary: |
    More picky version of Python dictionary.
    PickyDict objects will behave just like Python dictionaries, with a few notable exceptions.
    PickyDict has a force_lower_case attribute. and PickyDict can contain two additional dictionaries
    named key_replacements and key_regex_replacements with mappings to enforce translating specific key words.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - florian-huber
